/**
 * Music genre constants
 * Comprehensive list of genres sorted alphabetically
 */

export const GENRES = [
  'African',
  'African Dancehall',
  'African Reggae',
  'Afrikaans',
  'Afro House',
  'Afro Soul',
  'Afro-Beat',
  'Afro-folk',
  'Afro-fusion',
  'Afro-Pop',
  'Afrobeats',
  'Alte',
  'Amapiano',
  'Benga',
  'Bongo-Flava',
  'Chimurenga',
  'Coupé-Décalé',
  'Fuji',
  'Genge',
  'Gqom',
  'Highlife',
  'Kizomba',
  'Kuduro',
  'Kwaito',
  'Kwassa',
  'Mapouka',
  'Maskandi',
  'Mbalax',
  'Ndombolo',
  'Shangaan Electro',
  'Soukous',
  'Taarab',
  'Zouglou',
  'Alternative',
  'Chinese Alt',
  'College Rock',
  'EMO',
  'Goth Rock',
  'Grunge',
  'Indie Egyptian',
  'Indie Levant',
  'Indie Maghreb',
  'Indie Pop',
  'Indie Rock',
  'Korean Indie',
  'New Wave',
  'Pop Punk',
  'Punk',
  'Turkish Alternative',
  'Anime',
  'Arabic',
  'Arabic Pop',
  'Islamic',
  'Khaleeji',
  'Khaleeji Jalsat',
  'Khaleeji Shailat',
  'Levant',
  'Dabke',
  'Maghreb Rai',
  'North African',
  'Blues',
  'Acoustic Blues',
  'Chicago Blues',
  'Classic Blues',
  'Contemporary Blues',
  'Country Blues',
  'Delta Blues',
  'Electric Blues',
  'Brazilian',
  'Axé',
  'Baile Funk',
  'Bossa Nova',
  'Choro',
  'Forró',
  'Frevo',
  'MPB',
  'Pagode',
  'Samba',
  'Sertanejo',
  "Children's Music",
  'Lullabies',
  'Sing-Along',
  'Stories',
  'Chinese',
  'Chinese Classical',
  'Chinese Flute',
  'Chinese Opera',
  'Chinese Orchestral',
  'Chinese Regional Folk',
  'Chinese Strings',
  'Taiwanese Folk',
  'Tibetan Native Music',
  'Christian & Gospel',
  'CCM',
  'Christian Metal',
  'Christian Pop',
  'Christian Rap',
  'Christian Rock',
  'Classic Christian',
  'Contemporary Gospel',
  'Gospel',
  'Praise & Worship',
  'Southern Gospel',
  'Traditional Gospel',
  'Classical',
  'Art Song',
  'Avant-Garde',
  'Baroque Era',
  'Brass & Woodwinds',
  'Cantata',
  'Cello',
  'Chamber Music',
  'Chant',
  'Choral',
  'Classical Crossover',
  'Classical Era',
  'Contemporary Era',
  'Electronic',
  'Guitar',
  'Impressionist',
  'Medieval Era',
  'Minimalism',
  'Modern Era',
  'Opera',
  'Oratorio',
  'Orchestral',
  'Percussion',
  'Piano',
  'Renaissance',
  'Romantic Era',
  'Sacred',
  'Solo Instrumental',
  'Violin',
  'Comedy',
  'Novelty',
  'Standup Comedy',
  'Country',
  'Alternative Country',
  'Americana',
  'Bluegrass',
  'Contemporary Bluegrass',
  'Contemporary Country',
  'Country Gospel',
  'Country Hip-Hop/Rap',
  'Honky Tonk',
  'Outlaw Country',
  'Thai Country',
  'Traditional Bluegrass',
  'Traditional Country',
  'Urban Cowboy',
  'Cuban',
  'Bolero',
  'Chachacha',
  'Guajira',
  'Guaracha',
  'Mambo',
  'Son',
  'Timba',
  'Dance',
  'Breakbeat',
  'Garage',
  'Hardcore',
  'House',
  "Jungle/Drum'n'bass",
  'Maghreb Dance',
  'Techno',
  'Trance',
  'Disney',
  'Easy Listening',
  'Lounge',
  'Swing',
  'Ambient',
  'Bass',
  'Downtempo',
  'Dubstep',
  "Electro-Cha'abi",
  'Electronica',
  'IDM/Experimental',
  'Industrial',
  'Levant Electronic',
  'Maghreb Electronic',
  'Enka',
  'Fitness & Workout',
  'Folk',
  'Iraqi Folk',
  'Khaleeji Folk',
  'French Pop',
  'German Folk',
  'German Pop',
  'Hip Hop/Rap',
  'Alternative Rap',
  'Chinese Hip-Hop',
  'Dirty South',
  'East Coast Rap',
  'Egyptian Hip-Hop',
  'Gangsta Rap',
  'Ghanaian Drill',
  'Hardcore Rap',
  'Hip-Hop',
  'Khaleeji Hip-Hop',
  'Korean Hip-Hop',
  'Latin Rap',
  'Levant Hip-Hop',
  'Maghreb Hip-Hop',
  'Old School Rap',
  'Rap',
  'Russian Hip-Hop',
  'South African Hip-Hop',
  'Turkish Hip-Hop/Rap',
  'UK Hip Hop',
  'Underground Rap',
  'West Coast Rap',
  'Holiday',
  'Christmas',
  "Christmas: Children's",
  'Christmas: Classic',
  'Christmas: Classical',
  'Christmas: Country',
  'Christmas: Jazz',
  'Christmas: Modern',
  'Christmas: Pop',
  'Christmas: R&B',
  'Christmas: Religious',
  'Christmas: Rock',
  'Easter',
  'Halloween',
  'Thanksgiving',
  'Hörspiele',
  'Indian',
  'Bollywood',
  'Devotional & Spiritual',
  'Ghazals',
  'Indian Classical',
  'Carnatic Classical',
  'Hindustani Classical',
  'Indian Folk',
  'Indian Pop',
  'Regional Indian',
  'Assamese',
  'Bengali',
  'Rabindra Sangeet',
  'Bhojpuri',
  'Gujarati',
  'Haryanvi',
  'Kannada',
  'Malayalam',
  'Marathi',
  'Odia',
  'Punjabi',
  'Punjabi Pop',
  'Rajasthani',
  'Tamil',
  'Telugu',
  'Urdu',
  'Sufi',
  'Inspirational',
  'Instrumental',
  'J-Pop',
  'Jazz',
  'Avant-Garde Jazz',
  'Bebop',
  'Big Band',
  'Contemporary Jazz',
  'Cool Jazz',
  'Crossover Jazz',
  'Dixieland',
  'Ethio Jazz',
  'Fusion',
  'Hard Bop',
  'Latin Jazz',
  'Mainstream Jazz',
  'Ragtime',
  'Smooth Jazz',
  'Trad Jazz',
  'Vocal Jazz',
  'Jewish',
  'Jewish Holidays',
  'Klezmer',
  'Karaoke',
  'Kayokyoku',
  'Korean',
  'Korean Traditional',
  'Latin',
  'Alternative & Rock in Spanish',
  'Baladas y Boleros',
  'Contemporary Latin',
  'Latin Urban',
  'Pop in Spanish',
  'Raices',
  'Regional Mexicano',
  'Salsa y Tropical',
  'Marching Bands',
  'New Age',
  'Healing',
  'Meditation',
  'Nature',
  'Relaxation',
  'Travel',
  'Yoga',
  'Pop',
  'Adult Contemporary',
  'Britpop',
  'Cantopop',
  'Egyptian Pop',
  'Indo Pop',
  'Iraqi Pop',
  'K-Pop',
  'Khaleeji Pop',
  'Korean Folk-Pop',
  'Levant Pop',
  'Maghreb Pop',
  'Malaysian Pop',
  'Mandopop',
  'Manilla Sound',
  'Oldies',
  'Original Pilipino Music',
  'Pinoy Pop',
  'Pop/Rock',
  'Russian Pop',
  'Shows',
  'Soft Rock',
  'T-Pop',
  'Tai-Pop',
  'Teen Pop',
  'Thai Pop',
  'Turkish Pop',
  'R&B/Soul',
  'Contemporary R&B',
  'Disco',
  'Doo Wop',
  'Funk',
  'Motown',
  'Neo-Soul',
  'Soul',
  'Reggae',
  'Dub',
  'Lovers Rock',
  'Modern Dancehall',
  'Roots Reggae',
  'Ska',
  'Rock',
  'Adult Alternative',
  'American Trad Rock',
  'Arena Rock',
  'Blues-Rock',
  'British Invasion',
  'Chinese Rock',
  'Death Metal/Black Metal',
  'Glam Rock',
  'Hair Metal',
  'Hard Rock',
  'Heavy Metal',
  'Jam Bands',
  'Korean Rock',
  'Prog-Rock/Art Rock',
  'Psychedelic',
  'Rock & Roll',
  'Rockabilly',
  'Roots Rock',
  'Russian Rock',
  'Singer/Songwriter',
  'Southern Rock',
  'Surf',
  'Tex-Mex',
  'Turkish Rock',
  'Russian',
  'Russian Bard',
  'Russian Chanson',
  'Russian Romance',
  'Alternative Folk',
  'Contemporary Folk',
  'Contemporary Singer/Songwriter',
  'Folk-Rock',
  'New Acoustic',
  'Traditional Folk',
  'Soundtrack',
  'Foreign Cinema',
  'Musicals',
  'Original Score',
  'Sound Effects',
  'TV Soundtrack',
  'Video Game',
  'Spoken Word',
  'Tarab',
  'Egyptian Tarab',
  'Iraqi Tarab',
  'Khaleeji Tarab',
  'Turkish',
  'Arabesk',
  'Fantezi',
  'Halk',
  'Religious',
  'Sanat',
  'Özgün',
  'Vocal',
  'Standards',
  'Traditional Pop',
  'Trot',
  'Vocal Pop',
  'Worldwide',
  'Asia',
  'Australia',
  'Cajun',
  'Calypso',
  'Caribbean',
  'Celtic',
  'Celtic Folk',
  'Contemporary Celtic',
  'Dangdut',
  'Dini',
  'Europe',
  'Fado',
  'Farsi',
  'Flamenco',
  'France',
  'Hawaii',
  'Iberia',
  'Indonesian Religious',
  'Israeli',
  'Japan',
  'North America',
  'Polka',
  'Soca',
  'South Africa',
  'South America',
  'Tango',
  'Traditional Celtic',
  'Worldbeat',
  'Zydeco',
].sort();
